name: Contracts CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PK: 123456789abcdef123456789abcdef123456789abcdef123456789abcdef1234
    name: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - run: npm install
      - run: npm contracts:compile
      - run: npm contracts:lint
      - run: npm contracts:format
      - run: npm tests:lint
      - run: npm tests:format

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      PK: 123456789abcdef123456789abcdef123456789abcdef123456789abcdef1234
    name: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - run: npm install
      - run: npm tests:unit
